set_property IOSTANDARD LVCMOS33 [get_ports {oData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[6]}]
set_property PACKAGE_PIN L18 [get_ports {oData[6]}]
set_property PACKAGE_PIN T11 [get_ports {oData[5]}]
set_property PACKAGE_PIN P15 [get_ports {oData[4]}]
set_property PACKAGE_PIN K13 [get_ports {oData[3]}]
set_property PACKAGE_PIN K16 [get_ports {oData[2]}]
set_property PACKAGE_PIN R10 [get_ports {oData[1]}]
set_property PACKAGE_PIN T10 [get_ports {oData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports DREQ]
set_property IOSTANDARD LVCMOS33 [get_ports nxt]
set_property IOSTANDARD LVCMOS33 [get_ports play]
set_property IOSTANDARD LVCMOS33 [get_ports pre]
set_property IOSTANDARD LVCMOS33 [get_ports SCK]
set_property IOSTANDARD LVCMOS33 [get_ports SI]
set_property IOSTANDARD LVCMOS33 [get_ports SO]
set_property IOSTANDARD LVCMOS33 [get_ports XCS]
set_property IOSTANDARD LVCMOS33 [get_ports XDCS]
set_property IOSTANDARD LVCMOS33 [get_ports XRESET]

set_property PACKAGE_PIN M17 [get_ports nxt]
set_property PACKAGE_PIN P17 [get_ports pre]
set_property PACKAGE_PIN K1 [get_ports XDCS]
set_property PACKAGE_PIN F6 [get_ports XRESET]
set_property PACKAGE_PIN E7 [get_ports XCS]
set_property PACKAGE_PIN E6 [get_ports SO]
set_property PACKAGE_PIN J4 [get_ports SI]
set_property PACKAGE_PIN J3 [get_ports SCK]
set_property PACKAGE_PIN J2 [get_ports DREQ]
set_property PACKAGE_PIN L16 [get_ports play]

set_property IOSTANDARD LVCMOS33 [get_ports {position[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN U13 [get_ports {position[7]}]
set_property PACKAGE_PIN K2 [get_ports {position[6]}]
set_property PACKAGE_PIN T14 [get_ports {position[5]}]
set_property PACKAGE_PIN P14 [get_ports {position[4]}]
set_property PACKAGE_PIN J14 [get_ports {position[3]}]
set_property PACKAGE_PIN T9 [get_ports {position[2]}]
set_property PACKAGE_PIN J18 [get_ports {position[1]}]
set_property PACKAGE_PIN J17 [get_ports {position[0]}]
set_property PACKAGE_PIN P18 [get_ports down]
set_property PACKAGE_PIN M18 [get_ports up]



set_property PACKAGE_PIN V10 [get_ports ena]
set_property IOSTANDARD LVCMOS33 [get_ports ena]


set_property IOSTANDARD LVCMOS33 [get_ports RXD]
set_property PACKAGE_PIN H14 [get_ports RXD]


set_property IOSTANDARD LVCMOS33 [get_ports DIN]
set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property IOSTANDARD LVCMOS33 [get_ports DC]
set_property IOSTANDARD LVCMOS33 [get_ports OLED_CLK]
set_property PACKAGE_PIN C17 [get_ports DIN]
set_property PACKAGE_PIN G17 [get_ports DC]
set_property PACKAGE_PIN D18 [get_ports OLED_CLK]
set_property PACKAGE_PIN D17 [get_ports RES]
set_property IOSTANDARD LVCMOS33 [get_ports RES]

set_property IOSTANDARD LVCMOS33 [get_ports TXD]
set_property PACKAGE_PIN G16 [get_ports TXD]

set_property IOSTANDARD LVCMOS33 [get_ports signal]

set_property PACKAGE_PIN N17 [get_ports signal]

set_property PACKAGE_PIN E18 [get_ports CS]
